version: '3'
services:
    maptomethod:
      image: ghcr.io/mat-o-lab/maptomethod:latest
      environment:
        - APP_MODE=development
      container_name: maptomethod
      ports:
        - ${APP_PORT}:5000
      restart: always
      networks:
        maptomethod_net:
networks:
  maptomethod_net:
    name: maptomethod_net
    driver: bridge
