version: '3'
services:
    maptomethod:
      build: .
      container_name: maptomethod
      #command: bash -c "gunicorn -c /src/gunicorn_conf.py wsgi:app -b 0.0.0.0:5000"
      #volumes:
      #  - ./:/src
      expose:
        - "5000"
      restart: always
      networks:
        app_deploy:
networks:
  app_deploy:
    driver: bridge

