version: '3.7'
services:
    maptomethod:
      build: .
      container_name: maptomethod
      ports:
         - 5005:5000
      restart: always
      networks:
        maptomethod_net:
networks:
  maptomethod_net:
    driver: bridge
