version: '3.7'
services:
    maptomethod:
      build: .
      environment:
        - APP_MODE = 'development'
      container_name: maptomethod
      ports:
        - 5005:5000
      volumes:
        - .:/src
      restart: always
      networks:
        maptomethod_net:
networks:
  maptomethod_net:
    driver: bridge
